spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
      show_sql: false
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:demo_data.sql

security:
  jwt:
    secretKey: Zmdocmhlc3IzMjRoY3hydDM0dGhzZTU0dTkwLTA5
    tokenExpiration: 5m
    refreshTokenExpiration: 30m