spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
      show_sql: false

  flyway:
    default-schema: tasklist
    init-sqls: create schema if not exists tasklist;

security:
  jwt:
    secretKey: Zmdocmhlc3IzMjRoY3hydDM0dGhzZTU0dTkwLTA5
    tokenExpiration: 5m
    refreshTokenExpiration: 30m

  cors:
    allowedOrigins: "*"
    allowedMethods: "*"
    allowedHeaders: "*"
    exposedHeaders: "*"
