create table if not exists users
(
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    username varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists tasks
(
    id              bigint generated by default as identity primary key,
    title           varchar(255) not null,
    description     varchar(255),
    status          varchar(255) not null,
    owner_id        bigint references users(id) on delete cascade,
    expiration_date timestamp(6)
);
